### ISSUE TITLE
com.coditory.sherlock.ReactiveSherlockWithConnectorBuilder.ReactiveSherlockApiMapper - Not visible

### ISSUE THREAD

**Issue by regbo** [coditory/sherlock-distributed-lock#63]
The following does not compile if the code isn't in the "com.coditory.sherlock":

```
  ReactorSherlock sherlock = reactiveMongoSherlock()
                .withClock(Clock.systemDefaultZone())
                .withLockDuration(Duration.ofMinutes(5))
                .withUniqueOwnerId()
                .withLocksCollection(locksCollection())
                .buildWithApi(ReactorSherlock::reactorSherlock);
```
The class com.coditory.sherlock.ReactiveSherlockWithConnectorBuilde is only visible at the package level, making ReactiveSherlockApiMapper  inaccessible.

Here is a workaround:

```
	ReactiveSherlock reactiveSherlock = reactiveMongoSherlock().withClock(Clock.systemDefaultZone())
				.withLockDuration(Duration.ofMinutes(5)).withUniqueOwnerId().withLocksCollection(locksCollection())
				.build();
		var reactorSherlock = ReactorSherlock.reactorSherlock(reactiveSherlock);
```

**Comment by pmendelski** [comment]
Hi, thanks for opening the issue.

I failed to reproduce the problem in a [separate project](https://github.com/coditory/sherlock-distributed-lock-sample/blob/master/sherlock-mongo-reactor/src/main/java/com/coditory/sandbox/sherlock/SherlockMongoReactive.java).
Could you please create PR with you settings?
