### ISSUE TITLE
Not able run in java 8 

### ISSUE THREAD

**Issue by p3manas** [coditory/sherlock-distributed-lock#64]
My application is supporting in java 8.
but when i am trying to run, getting exception.

Below dependency I have used.  Let me know if anything i have to do for this
<dependency>
<groupId>com.coditory.sherlock</groupId>
<artifactId>sherlock-common</artifactId>
<version>0.4.4</version>
<scope>runtime</scope>
</dependency>

**Comment by pmendelski** [comment]
Please update to java 11.
