### ISSUE TITLE
';' in SQL queries

### ISSUE THREAD

**Issue by jdhu** [coditory/sherlock-distributed-lock#65]
Hello,

In the class SqlQueries, there are some queries that include the ';'. Oracle fails when sending that character in a JDBC query. Would it be possible to remove them ?

Kind regards, and thanks a lot for this library :-)

Julien

**Comment by pmendelski** [comment]
Hi, thanks for kind words.
I removed all semicolons from SqlQueries.
Please try version 0.4.14.
