### ISSUE TITLE
Critical vulnerability in dependencies

### ISSUE THREAD

**Issue by neoscaler** [coditory/sherlock-distributed-lock#76]
The latest version contains a critical vulnerability and should get updated asap. The MRs from Dependabot are already there. Could you @pmendelski do an release with updated dependencies or is this project abandoned?

**Comment by pmendelski** [comment]
Hi @neoscaler
I've just released v1.4.16 where all dependencies are up to date

**Comment by neoscaler** [comment]
Thanks a lot for the prompt action!

**Comment by pmendelski** [comment]
@neoscaler  Thanks for posting this issue.
You're right it should have been released earlier.
