### ISSUE TITLE
Lock mechanism not working with H2 database

### ISSUE THREAD

**Issue by neoscaler** [coditory/sherlock-distributed-lock#99]
We run our local tests with a H2 database. There we noticed that Sherlock isn't working as expected and its seems that this line is the cause for it:

https://github.com/coditory/sherlock-distributed-lock/blob/8ab33dba19b1059b4b86ec49b6e91ec65fe50853/sql/src/main/java/com/coditory/sherlock/SqlDistributedLockConnector.java#L117

With H2 the exception does not contain the word 'duplicate', instead it's in German (locale settings probably) and saying 'Eindeutiger Index oder Primärschlüssel verletzt'.

//edit:
In english it's '23505=Unique index or primary key violation: {0}'

**Comment by pmendelski** [comment]
@neoscaler Please try `v0.4.19` and let us know. I was pretty sure it will blow up someday. Thanks for filing the issue.

**Comment by neoscaler** [comment]
> @neoscaler Please try `v0.4.19` and let us know. I was pretty sure it will blow up someday. Thanks for filing the issue.

Tested it and works like a charm. Thanks a lot for the fast fix!
